save_path: './genset'
condition_file: './dataset/event_tensor/MIDI-UNPROCESSED_01-03_R1_2014_MID--AUDIO_02_R1_2014_wav--2.pt' 
length: 1000
threshold_len: 512


max_seq: 1024
embedding_dim: 512
num_layers: 10
event_dim: 484
experiment: 'initial'
condition_length: 100