save_path: './genset'
condition_file: #'./dataset_test/event_tensor/chpn_op23.pt'
length: 1000
threshold_len: 512


max_seq: 512
embedding_dim: 512
num_layers: 6
event_dim: 484
experiment: 'initial'
condition_length: 400