pickle_dir: './dataset/pickle'
epochs: 3000
batch_size: 32
load_path: 
dropout: 0.1
debug: 'false'
label_smooth: 0.1

max_seq: 512
embedding_dim: 512
num_layers: 6
event_dim: 388
experiment: 'small_data'