pickle_dir: './dataset/event_tensor'
epochs: 5000
batch_size: 32
load_path: 'results/train-200.pth'
dropout: 0.1
debug: 'false'
label_smooth: 0.1

max_seq: 512
embedding_dim: 512
num_layers: 6
event_dim: 484
experiment: 'small_data'