pickle_dir: './processed'
epochs: 1000
batch_size: 4
load_path:
dropout: 0.1
debug: 'true'
l_r: 0.001
label_smooth: 0.1

max_seq: 128
embedding_dim: 512
num_layers: 6
event_dim: 388
experiment: 'initial'