model:
  d_ff: 128
  d_hidden: 128
  d_embed: 128
  dropout: 0.1
  data_len: 128
  n_head: 8
  num_layers: 6
  num_tokens: 385
  padding_idx: 384

log:
  checkpoint_dir: 'checkpoints'
  log_dir: 'logs'
  name: 'test'
  trace: False
  version: 0

data:
  num_workers: 0
  datamidi_dir: 'dataset/midi'
  max_len: 16384
  make_note_tensor: False
  notetensor_dir: 'dataset/note_tensor'

train:
  accumulate: 1
  batch_size: 2
  betas: [0.5, 0.9]
  epochs: 1500
  fast_dev_run: False
  gpus: 1
  lr: 0.0003
  optim: 'adam'
  resume: ''
  save_top_k: 3
  steps: 100
  time_loss_mode: 'one_hot'
  valid_split: 1024

inference:
  sample: False
  length: 1
  path: ''
  save_path: 'samples'
