model:
  d_ff: 2048
  d_hidden: 512
  d_embed: 512
  dropout: 0.1
  data_len: 2048
  n_head: 8
  num_layers: 6
  num_tokens: 385
  padding_idx: 384

log:
  checkpoint_dir: 'checkpoints'
  log_dir: 'logs'
  name: 'test'
  trace: False
  version: 0

data:
  num_workers: 32
  dataset_path: ''
  max_len: 16384

train:
  accumulate: 1
  batch_size: 64
  betas: [0.5, 0.9]
  epochs: 1500
  fast_dev_run: False
  gpus: 1
  lr: 0.0003
  optim: 'adam'
  resume: ''
  save_top_k: 3
  steps: 100
  time_loss_mode: 'one_hot'
  valid_split: 1024

inference:
  sample: False
  length: 1
  path: ''
  save_path: 'samples'
