defaults:
  - dataset: full
  - optimizer: adam

model:
  size: 10

train:
  accumulate: 1
  batch_size: 64
  betas: [0.5, 0.9]
  checkpoint_dir: 'checkpoints'
  epochs: 1500
  fast_dev_run: False
  gpus: 2
  lr: 0.0003
  log_dir: 'logs'
  name: 'test'
  parallel_calls: 32
  sample: False
  save_top_k: 3
  steps: 100
  trace: False
  valid_split: 1024
  version: 0

inference:
  length: 1
  path: ''
  save_path: 'samples'
