model:
  num_layer: 10
  embedding_dim: 512
  max_seq: 1024
  vocab_size: 484
  dropout: 0.1

dataset:
  dir_path: './dataset/midi'

train:
  optim: 'adam'
  accumulate: 1
  batch_size: 32
  betas: [0.5, 0.9]
  checkpoint_dir: 'checkpoints'
  epochs: 10000
  fast_dev_run: False
  gpus: 4
  lr: 0.0003
  log_dir: 'logs'
  name: 'test'
  parallel_calls: 32
  resume: #'outputs/2021-01-29/14-38-06/checkpoints/epoch=5459-step=21839.ckpt'
  sample: False
  save_top_k: 3
  steps: 1000
  trace: False
  valid_split: 1024
  version: 0
  random_seed: 42
  label_smooth: 0.1
  reduction: 'mean'

inference:
  length: 1
  checkpoint_path: 'outputs/2021-01-29/16-13-01/checkpoints/epoch=7575-step=30303.ckpt'
  save_path: 'samples'
  condition_pt: #'dataset/event_tensor/MIDI-Unprocessed_02_R1_2006_01-04_ORIG_MID--AUDIO_02_R1_2006_03_Track03_wav.pt'
  condition_length: 200
  inference_length: 1000