model:
  d_ff: 512
  d_hidden: 512
  d_embed: 512
  dropout: 0.1
  data_len: 512
  num_time_token: 500
  n_head: 4
  num_layers: 12
  num_tokens: 385
  padding_idx: 384
  sinusoid_const: 0.1
  use_temporal_encoding: True

log:
  checkpoint_dir: 'checkpoints'
  log_dir: 'logs'
  name: 'test'
  trace: False
  version: 0

data:
  datamidi_dir: 'dataset/midi'
  dataset_path: ''
  make_data_tensor: False
  max_len: 1000000
  datatensor_dir: 'dataset/time_token_tensor'
  num_workers: 4
  datamode: 'time_note_vel'

train:
  accumulate: 1
  batch_size: 8
  betas: [0.5, 0.9]
  epochs: 10000
  fast_dev_run: False
  gpus: 1
  lr: 0.00002
  optim: 'adam'
  resume: #'outputs\2021-02-11\00-26-37\checkpoints\ckpt-epoch=1736-val_loss=4.3259.ckpt'
  save_top_k: 3
  steps: 100
  time_loss_mode: 'one_hot'
  time_loss_mul: 1.0
  valid_split: 512

inference:
  length: 3000
  condition_pt: 'dataset/note_tensor/MIDI-Unprocessed_01_R1_2009_01-04_ORIG_MID--AUDIO_01_R1_2009_01_R1_2009_01_WAV.pt'
  condition_length: 100
  checkpoint_path: 'outputs/2021-02-17/00-47-26/checkpoints/ckpt-epoch=1736-val_loss=4.3259.ckpt'
  sample: False
  save_path: 'samples'
  sample_mode: 'OneHotCategorical'
  zero_threshold: 0.5
